
<?php
  /*
    Copyright 2010 Persistent Systems Limited

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
   */

    /**
    * This code was generated by the tool 'PHPDataSvcUtil.php'.
    * Runtime Version:1.0
    *
    * Changes to this file may cause incorrect behavior and will be lost if
    * the code is regenerated.
    */

    require_once 'Context/ObjectContext.php';
    /**
    * Defines default OData Service URL for this proxy class
    */
    define("DEFAULT_ODATA_SERVICE_URL", "http://bqapi.edgedatasystems.co.uk/BQWatchesNop.svc");
    
   /**
    * @class:Manufacturer
    * @type:EntityType
    * @key:Id
    */
    class Manufacturer extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Name;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Description;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ManufacturerTemplateId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $MetaKeywords;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $MetaDescription;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $MetaTitle;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:200
        * @FixedLength:false
        */
        public $SeName;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $PictureId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $PageSize;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $AllowCustomersToSelectPageSize;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:200
        * @FixedLength:false
        */
        public $PageSizeOptions;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $PriceRanges;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Published;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Deleted;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $DisplayOrder;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $UpdatedOnUtc;
    

       /**
        * Function to create an instance of Manufacturer
        * @param Edm.Int32 $Id
        * @param Edm.String $Name
        * @param Edm.Int32 $ManufacturerTemplateId
        * @param Edm.Int32 $PictureId
        * @param Edm.Int32 $PageSize
        * @param Edm.Boolean $AllowCustomersToSelectPageSize
        * @param Edm.Boolean $Published
        * @param Edm.Boolean $Deleted
        * @param Edm.Int32 $DisplayOrder
        * @param Edm.DateTime $CreatedOnUtc
        * @param Edm.DateTime $UpdatedOnUtc
        */
        public static function CreateManufacturer(
            $Id, 
            $Name, 
            $ManufacturerTemplateId, 
            $PictureId, 
            $PageSize, 
            $AllowCustomersToSelectPageSize, 
            $Published, 
            $Deleted, 
            $DisplayOrder, 
            $CreatedOnUtc, 
            $UpdatedOnUtc)
        {   
            $Manufacturer = new Manufacturer();
            $Manufacturer->Id = $Id;
            $Manufacturer->Name = $Name;
            $Manufacturer->ManufacturerTemplateId = $ManufacturerTemplateId;
            $Manufacturer->PictureId = $PictureId;
            $Manufacturer->PageSize = $PageSize;
            $Manufacturer->AllowCustomersToSelectPageSize = $AllowCustomersToSelectPageSize;
            $Manufacturer->Published = $Published;
            $Manufacturer->Deleted = $Deleted;
            $Manufacturer->DisplayOrder = $DisplayOrder;
            $Manufacturer->CreatedOnUtc = $CreatedOnUtc;
            $Manufacturer->UpdatedOnUtc = $UpdatedOnUtc;
            return $Manufacturer;
        }

       /**
        * Constructor for Manufacturer
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:Product
    * @type:EntityType
    * @key:Id
    */
    class Product extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Name;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $ShortDescription;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $FullDescription;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AdminComment;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductTemplateId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $ShowOnHomePage;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $MetaKeywords;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $MetaDescription;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $MetaTitle;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:200
        * @FixedLength:false
        */
        public $SeName;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $AllowCustomerReviews;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ApprovedRatingSum;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $NotApprovedRatingSum;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ApprovedTotalReviews;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $NotApprovedTotalReviews;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Published;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Deleted;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $UpdatedOnUtc;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:ProductVariant_Product
        * @FromRole:Product
        * @ToRole:ProductVariant
        */
        public $ProductVariants;
    

       /**
        * Function to create an instance of Product
        * @param Edm.Int32 $Id
        * @param Edm.String $Name
        * @param Edm.Int32 $ProductTemplateId
        * @param Edm.Boolean $ShowOnHomePage
        * @param Edm.Boolean $AllowCustomerReviews
        * @param Edm.Int32 $ApprovedRatingSum
        * @param Edm.Int32 $NotApprovedRatingSum
        * @param Edm.Int32 $ApprovedTotalReviews
        * @param Edm.Int32 $NotApprovedTotalReviews
        * @param Edm.Boolean $Published
        * @param Edm.Boolean $Deleted
        * @param Edm.DateTime $CreatedOnUtc
        * @param Edm.DateTime $UpdatedOnUtc
        */
        public static function CreateProduct(
            $Id, 
            $Name, 
            $ProductTemplateId, 
            $ShowOnHomePage, 
            $AllowCustomerReviews, 
            $ApprovedRatingSum, 
            $NotApprovedRatingSum, 
            $ApprovedTotalReviews, 
            $NotApprovedTotalReviews, 
            $Published, 
            $Deleted, 
            $CreatedOnUtc, 
            $UpdatedOnUtc)
        {   
            $Product = new Product();
            $Product->Id = $Id;
            $Product->Name = $Name;
            $Product->ProductTemplateId = $ProductTemplateId;
            $Product->ShowOnHomePage = $ShowOnHomePage;
            $Product->AllowCustomerReviews = $AllowCustomerReviews;
            $Product->ApprovedRatingSum = $ApprovedRatingSum;
            $Product->NotApprovedRatingSum = $NotApprovedRatingSum;
            $Product->ApprovedTotalReviews = $ApprovedTotalReviews;
            $Product->NotApprovedTotalReviews = $NotApprovedTotalReviews;
            $Product->Published = $Published;
            $Product->Deleted = $Deleted;
            $Product->CreatedOnUtc = $CreatedOnUtc;
            $Product->UpdatedOnUtc = $UpdatedOnUtc;
            return $Product;
        }

       /**
        * Constructor for Product
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
            $this->_entityMap['ProductVariants'] = 'ProductVariant';
            $this->ProductVariants = array();
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:ProductVariant
    * @type:EntityType
    * @key:Id
    */
    class ProductVariant extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Name;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Sku;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Description;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AdminComment;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $ManufacturerPartNumber;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Gtin;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsGiftCard;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $GiftCardTypeId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $RequireOtherProducts;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1000
        * @FixedLength:false
        */
        public $RequiredProductVariantIds;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $AutomaticallyAddRequiredProductVariants;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsDownload;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $DownloadId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $UnlimitedDownloads;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $MaxNumberOfDownloads;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $DownloadExpirationDays;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $DownloadActivationTypeId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $HasSampleDownload;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $SampleDownloadId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $HasUserAgreement;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $UserAgreementText;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsRecurring;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $RecurringCycleLength;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $RecurringCyclePeriodId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $RecurringTotalCycles;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsShipEnabled;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsFreeShipping;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $AdditionalShippingCharge;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsTaxExempt;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $TaxCategoryId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ManageInventoryMethodId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $StockQuantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $DisplayStockAvailability;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $DisplayStockQuantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $MinStockQuantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $LowStockActivityId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $NotifyAdminForQuantityBelow;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $BackorderModeId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $AllowBackInStockSubscriptions;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $OrderMinimumQuantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $OrderMaximumQuantity;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1000
        * @FixedLength:false
        */
        public $AllowedQuantities;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $DisableBuyButton;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $DisableWishlistButton;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $AvailableForPreOrder;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $CallForPrice;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $Price;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OldPrice;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $ProductCost;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $SpecialPrice;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $SpecialPriceStartDateTimeUtc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $SpecialPriceEndDateTimeUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $CustomerEntersPrice;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $MinimumCustomerEnteredPrice;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $MaximumCustomerEnteredPrice;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $HasTierPrices;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $HasDiscountsApplied;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $Weight;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $Length;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $Width;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $Height;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $PictureId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $AvailableStartDateTimeUtc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $AvailableEndDateTimeUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Published;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Deleted;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $DisplayOrder;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $UpdatedOnUtc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $StockId;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:ProductVariant_Product
        * @FromRole:ProductVariant
        * @ToRole:Product
        */
        public $Product;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:OrderProductVariant_ProductVariant
        * @FromRole:ProductVariant
        * @ToRole:OrderProductVariant
        */
        public $OrderProductVariants;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:ShoppingCartItem_ProductVariant
        * @FromRole:ProductVariant
        * @ToRole:ShoppingCartItem
        */
        public $ShoppingCartItems;
    

       /**
        * Function to create an instance of ProductVariant
        * @param Edm.Int32 $Id
        * @param Edm.Int32 $ProductId
        * @param Edm.Boolean $IsGiftCard
        * @param Edm.Int32 $GiftCardTypeId
        * @param Edm.Boolean $RequireOtherProducts
        * @param Edm.Boolean $AutomaticallyAddRequiredProductVariants
        * @param Edm.Boolean $IsDownload
        * @param Edm.Int32 $DownloadId
        * @param Edm.Boolean $UnlimitedDownloads
        * @param Edm.Int32 $MaxNumberOfDownloads
        * @param Edm.Int32 $DownloadActivationTypeId
        * @param Edm.Boolean $HasSampleDownload
        * @param Edm.Int32 $SampleDownloadId
        * @param Edm.Boolean $HasUserAgreement
        * @param Edm.Boolean $IsRecurring
        * @param Edm.Int32 $RecurringCycleLength
        * @param Edm.Int32 $RecurringCyclePeriodId
        * @param Edm.Int32 $RecurringTotalCycles
        * @param Edm.Boolean $IsShipEnabled
        * @param Edm.Boolean $IsFreeShipping
        * @param Edm.Decimal $AdditionalShippingCharge
        * @param Edm.Boolean $IsTaxExempt
        * @param Edm.Int32 $TaxCategoryId
        * @param Edm.Int32 $ManageInventoryMethodId
        * @param Edm.Int32 $StockQuantity
        * @param Edm.Boolean $DisplayStockAvailability
        * @param Edm.Boolean $DisplayStockQuantity
        * @param Edm.Int32 $MinStockQuantity
        * @param Edm.Int32 $LowStockActivityId
        * @param Edm.Int32 $NotifyAdminForQuantityBelow
        * @param Edm.Int32 $BackorderModeId
        * @param Edm.Boolean $AllowBackInStockSubscriptions
        * @param Edm.Int32 $OrderMinimumQuantity
        * @param Edm.Int32 $OrderMaximumQuantity
        * @param Edm.Boolean $DisableBuyButton
        * @param Edm.Boolean $DisableWishlistButton
        * @param Edm.Boolean $AvailableForPreOrder
        * @param Edm.Boolean $CallForPrice
        * @param Edm.Decimal $Price
        * @param Edm.Decimal $OldPrice
        * @param Edm.Decimal $ProductCost
        * @param Edm.Boolean $CustomerEntersPrice
        * @param Edm.Decimal $MinimumCustomerEnteredPrice
        * @param Edm.Decimal $MaximumCustomerEnteredPrice
        * @param Edm.Boolean $HasTierPrices
        * @param Edm.Boolean $HasDiscountsApplied
        * @param Edm.Decimal $Weight
        * @param Edm.Decimal $Length
        * @param Edm.Decimal $Width
        * @param Edm.Decimal $Height
        * @param Edm.Int32 $PictureId
        * @param Edm.Boolean $Published
        * @param Edm.Boolean $Deleted
        * @param Edm.Int32 $DisplayOrder
        * @param Edm.DateTime $CreatedOnUtc
        * @param Edm.DateTime $UpdatedOnUtc
        */
        public static function CreateProductVariant(
            $Id, 
            $ProductId, 
            $IsGiftCard, 
            $GiftCardTypeId, 
            $RequireOtherProducts, 
            $AutomaticallyAddRequiredProductVariants, 
            $IsDownload, 
            $DownloadId, 
            $UnlimitedDownloads, 
            $MaxNumberOfDownloads, 
            $DownloadActivationTypeId, 
            $HasSampleDownload, 
            $SampleDownloadId, 
            $HasUserAgreement, 
            $IsRecurring, 
            $RecurringCycleLength, 
            $RecurringCyclePeriodId, 
            $RecurringTotalCycles, 
            $IsShipEnabled, 
            $IsFreeShipping, 
            $AdditionalShippingCharge, 
            $IsTaxExempt, 
            $TaxCategoryId, 
            $ManageInventoryMethodId, 
            $StockQuantity, 
            $DisplayStockAvailability, 
            $DisplayStockQuantity, 
            $MinStockQuantity, 
            $LowStockActivityId, 
            $NotifyAdminForQuantityBelow, 
            $BackorderModeId, 
            $AllowBackInStockSubscriptions, 
            $OrderMinimumQuantity, 
            $OrderMaximumQuantity, 
            $DisableBuyButton, 
            $DisableWishlistButton, 
            $AvailableForPreOrder, 
            $CallForPrice, 
            $Price, 
            $OldPrice, 
            $ProductCost, 
            $CustomerEntersPrice, 
            $MinimumCustomerEnteredPrice, 
            $MaximumCustomerEnteredPrice, 
            $HasTierPrices, 
            $HasDiscountsApplied, 
            $Weight, 
            $Length, 
            $Width, 
            $Height, 
            $PictureId, 
            $Published, 
            $Deleted, 
            $DisplayOrder, 
            $CreatedOnUtc, 
            $UpdatedOnUtc)
        {   
            $ProductVariant = new ProductVariant();
            $ProductVariant->Id = $Id;
            $ProductVariant->ProductId = $ProductId;
            $ProductVariant->IsGiftCard = $IsGiftCard;
            $ProductVariant->GiftCardTypeId = $GiftCardTypeId;
            $ProductVariant->RequireOtherProducts = $RequireOtherProducts;
            $ProductVariant->AutomaticallyAddRequiredProductVariants = $AutomaticallyAddRequiredProductVariants;
            $ProductVariant->IsDownload = $IsDownload;
            $ProductVariant->DownloadId = $DownloadId;
            $ProductVariant->UnlimitedDownloads = $UnlimitedDownloads;
            $ProductVariant->MaxNumberOfDownloads = $MaxNumberOfDownloads;
            $ProductVariant->DownloadActivationTypeId = $DownloadActivationTypeId;
            $ProductVariant->HasSampleDownload = $HasSampleDownload;
            $ProductVariant->SampleDownloadId = $SampleDownloadId;
            $ProductVariant->HasUserAgreement = $HasUserAgreement;
            $ProductVariant->IsRecurring = $IsRecurring;
            $ProductVariant->RecurringCycleLength = $RecurringCycleLength;
            $ProductVariant->RecurringCyclePeriodId = $RecurringCyclePeriodId;
            $ProductVariant->RecurringTotalCycles = $RecurringTotalCycles;
            $ProductVariant->IsShipEnabled = $IsShipEnabled;
            $ProductVariant->IsFreeShipping = $IsFreeShipping;
            $ProductVariant->AdditionalShippingCharge = $AdditionalShippingCharge;
            $ProductVariant->IsTaxExempt = $IsTaxExempt;
            $ProductVariant->TaxCategoryId = $TaxCategoryId;
            $ProductVariant->ManageInventoryMethodId = $ManageInventoryMethodId;
            $ProductVariant->StockQuantity = $StockQuantity;
            $ProductVariant->DisplayStockAvailability = $DisplayStockAvailability;
            $ProductVariant->DisplayStockQuantity = $DisplayStockQuantity;
            $ProductVariant->MinStockQuantity = $MinStockQuantity;
            $ProductVariant->LowStockActivityId = $LowStockActivityId;
            $ProductVariant->NotifyAdminForQuantityBelow = $NotifyAdminForQuantityBelow;
            $ProductVariant->BackorderModeId = $BackorderModeId;
            $ProductVariant->AllowBackInStockSubscriptions = $AllowBackInStockSubscriptions;
            $ProductVariant->OrderMinimumQuantity = $OrderMinimumQuantity;
            $ProductVariant->OrderMaximumQuantity = $OrderMaximumQuantity;
            $ProductVariant->DisableBuyButton = $DisableBuyButton;
            $ProductVariant->DisableWishlistButton = $DisableWishlistButton;
            $ProductVariant->AvailableForPreOrder = $AvailableForPreOrder;
            $ProductVariant->CallForPrice = $CallForPrice;
            $ProductVariant->Price = $Price;
            $ProductVariant->OldPrice = $OldPrice;
            $ProductVariant->ProductCost = $ProductCost;
            $ProductVariant->CustomerEntersPrice = $CustomerEntersPrice;
            $ProductVariant->MinimumCustomerEnteredPrice = $MinimumCustomerEnteredPrice;
            $ProductVariant->MaximumCustomerEnteredPrice = $MaximumCustomerEnteredPrice;
            $ProductVariant->HasTierPrices = $HasTierPrices;
            $ProductVariant->HasDiscountsApplied = $HasDiscountsApplied;
            $ProductVariant->Weight = $Weight;
            $ProductVariant->Length = $Length;
            $ProductVariant->Width = $Width;
            $ProductVariant->Height = $Height;
            $ProductVariant->PictureId = $PictureId;
            $ProductVariant->Published = $Published;
            $ProductVariant->Deleted = $Deleted;
            $ProductVariant->DisplayOrder = $DisplayOrder;
            $ProductVariant->CreatedOnUtc = $CreatedOnUtc;
            $ProductVariant->UpdatedOnUtc = $UpdatedOnUtc;
            return $ProductVariant;
        }

       /**
        * Constructor for ProductVariant
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
            $this->_entityMap['Product'] = 'Product';
            $this->_entityMap['OrderProductVariants'] = 'OrderProductVariant';
            $this->_entityMap['ShoppingCartItems'] = 'ShoppingCartItem';
            $this->Product = array();
            $this->OrderProductVariants = array();
            $this->ShoppingCartItems = array();
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:Order
    * @type:EntityType
    * @key:Id
    */
    class Order extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Guid
        */
        public $OrderGuid;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $CustomerId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $BillingAddressId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $ShippingAddressId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $OrderStatusId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ShippingStatusId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $PaymentStatusId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $PaymentMethodSystemName;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CustomerCurrencyCode;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $CurrencyRate;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $CustomerTaxDisplayTypeId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $VatNumber;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderSubtotalInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderSubtotalExclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderSubTotalDiscountInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderSubTotalDiscountExclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderShippingInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderShippingExclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $PaymentMethodAdditionalFeeInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $PaymentMethodAdditionalFeeExclTax;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $TaxRates;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderDiscount;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $OrderTotal;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $RefundedAmount;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $RewardPointsWereAdded;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CheckoutAttributeDescription;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CheckoutAttributesXml;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $CustomerLanguageId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $AffiliateId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CustomerIp;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $AllowStoringCreditCardNumber;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CardType;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CardName;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CardNumber;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $MaskedCreditCardNumber;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CardCvv2;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CardExpirationMonth;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CardExpirationYear;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AuthorizationTransactionId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AuthorizationTransactionCode;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AuthorizationTransactionResult;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CaptureTransactionId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CaptureTransactionResult;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $SubscriptionTransactionId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $PurchaseOrderNumber;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $PaidDateUtc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $ShippingMethod;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $ShippingRateComputationMethodSystemName;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Deleted;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:OrderProductVariant_Order
        * @FromRole:Order
        * @ToRole:OrderProductVariant
        */
        public $OrderProductVariants;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:Order_Customer
        * @FromRole:Order
        * @ToRole:Customer
        */
        public $Customer;
    

       /**
        * Function to create an instance of Order
        * @param Edm.Int32 $Id
        * @param Edm.Guid $OrderGuid
        * @param Edm.Int32 $CustomerId
        * @param Edm.Int32 $BillingAddressId
        * @param Edm.Int32 $OrderStatusId
        * @param Edm.Int32 $ShippingStatusId
        * @param Edm.Int32 $PaymentStatusId
        * @param Edm.Decimal $CurrencyRate
        * @param Edm.Int32 $CustomerTaxDisplayTypeId
        * @param Edm.Decimal $OrderSubtotalInclTax
        * @param Edm.Decimal $OrderSubtotalExclTax
        * @param Edm.Decimal $OrderSubTotalDiscountInclTax
        * @param Edm.Decimal $OrderSubTotalDiscountExclTax
        * @param Edm.Decimal $OrderShippingInclTax
        * @param Edm.Decimal $OrderShippingExclTax
        * @param Edm.Decimal $PaymentMethodAdditionalFeeInclTax
        * @param Edm.Decimal $PaymentMethodAdditionalFeeExclTax
        * @param Edm.Decimal $OrderTax
        * @param Edm.Decimal $OrderDiscount
        * @param Edm.Decimal $OrderTotal
        * @param Edm.Decimal $RefundedAmount
        * @param Edm.Boolean $RewardPointsWereAdded
        * @param Edm.Int32 $CustomerLanguageId
        * @param Edm.Boolean $AllowStoringCreditCardNumber
        * @param Edm.Boolean $Deleted
        * @param Edm.DateTime $CreatedOnUtc
        */
        public static function CreateOrder(
            $Id, 
            $OrderGuid, 
            $CustomerId, 
            $BillingAddressId, 
            $OrderStatusId, 
            $ShippingStatusId, 
            $PaymentStatusId, 
            $CurrencyRate, 
            $CustomerTaxDisplayTypeId, 
            $OrderSubtotalInclTax, 
            $OrderSubtotalExclTax, 
            $OrderSubTotalDiscountInclTax, 
            $OrderSubTotalDiscountExclTax, 
            $OrderShippingInclTax, 
            $OrderShippingExclTax, 
            $PaymentMethodAdditionalFeeInclTax, 
            $PaymentMethodAdditionalFeeExclTax, 
            $OrderTax, 
            $OrderDiscount, 
            $OrderTotal, 
            $RefundedAmount, 
            $RewardPointsWereAdded, 
            $CustomerLanguageId, 
            $AllowStoringCreditCardNumber, 
            $Deleted, 
            $CreatedOnUtc)
        {   
            $Order = new Order();
            $Order->Id = $Id;
            $Order->OrderGuid = $OrderGuid;
            $Order->CustomerId = $CustomerId;
            $Order->BillingAddressId = $BillingAddressId;
            $Order->OrderStatusId = $OrderStatusId;
            $Order->ShippingStatusId = $ShippingStatusId;
            $Order->PaymentStatusId = $PaymentStatusId;
            $Order->CurrencyRate = $CurrencyRate;
            $Order->CustomerTaxDisplayTypeId = $CustomerTaxDisplayTypeId;
            $Order->OrderSubtotalInclTax = $OrderSubtotalInclTax;
            $Order->OrderSubtotalExclTax = $OrderSubtotalExclTax;
            $Order->OrderSubTotalDiscountInclTax = $OrderSubTotalDiscountInclTax;
            $Order->OrderSubTotalDiscountExclTax = $OrderSubTotalDiscountExclTax;
            $Order->OrderShippingInclTax = $OrderShippingInclTax;
            $Order->OrderShippingExclTax = $OrderShippingExclTax;
            $Order->PaymentMethodAdditionalFeeInclTax = $PaymentMethodAdditionalFeeInclTax;
            $Order->PaymentMethodAdditionalFeeExclTax = $PaymentMethodAdditionalFeeExclTax;
            $Order->OrderTax = $OrderTax;
            $Order->OrderDiscount = $OrderDiscount;
            $Order->OrderTotal = $OrderTotal;
            $Order->RefundedAmount = $RefundedAmount;
            $Order->RewardPointsWereAdded = $RewardPointsWereAdded;
            $Order->CustomerLanguageId = $CustomerLanguageId;
            $Order->AllowStoringCreditCardNumber = $AllowStoringCreditCardNumber;
            $Order->Deleted = $Deleted;
            $Order->CreatedOnUtc = $CreatedOnUtc;
            return $Order;
        }

       /**
        * Constructor for Order
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
            $this->_entityMap['OrderProductVariants'] = 'OrderProductVariant';
            $this->_entityMap['Customer'] = 'Customer';
            $this->OrderProductVariants = array();
            $this->Customer = array();
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:OrderProductVariant
    * @type:EntityType
    * @key:Id
    */
    class OrderProductVariant extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Guid
        */
        public $OrderProductVariantGuid;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $OrderId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductVariantId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Quantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $UnitPriceInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $UnitPriceExclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $PriceInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $PriceExclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $DiscountAmountInclTax;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $DiscountAmountExclTax;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AttributeDescription;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AttributesXml;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $DownloadCount;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsDownloadActivated;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $LicenseDownloadId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Decimal
        */
        public $ItemWeight;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:OrderProductVariant_Order
        * @FromRole:OrderProductVariant
        * @ToRole:Order
        */
        public $Order;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:OrderProductVariant_ProductVariant
        * @FromRole:OrderProductVariant
        * @ToRole:ProductVariant
        */
        public $ProductVariant;
    

       /**
        * Function to create an instance of OrderProductVariant
        * @param Edm.Int32 $Id
        * @param Edm.Guid $OrderProductVariantGuid
        * @param Edm.Int32 $OrderId
        * @param Edm.Int32 $ProductVariantId
        * @param Edm.Int32 $Quantity
        * @param Edm.Decimal $UnitPriceInclTax
        * @param Edm.Decimal $UnitPriceExclTax
        * @param Edm.Decimal $PriceInclTax
        * @param Edm.Decimal $PriceExclTax
        * @param Edm.Decimal $DiscountAmountInclTax
        * @param Edm.Decimal $DiscountAmountExclTax
        * @param Edm.Int32 $DownloadCount
        * @param Edm.Boolean $IsDownloadActivated
        */
        public static function CreateOrderProductVariant(
            $Id, 
            $OrderProductVariantGuid, 
            $OrderId, 
            $ProductVariantId, 
            $Quantity, 
            $UnitPriceInclTax, 
            $UnitPriceExclTax, 
            $PriceInclTax, 
            $PriceExclTax, 
            $DiscountAmountInclTax, 
            $DiscountAmountExclTax, 
            $DownloadCount, 
            $IsDownloadActivated)
        {   
            $OrderProductVariant = new OrderProductVariant();
            $OrderProductVariant->Id = $Id;
            $OrderProductVariant->OrderProductVariantGuid = $OrderProductVariantGuid;
            $OrderProductVariant->OrderId = $OrderId;
            $OrderProductVariant->ProductVariantId = $ProductVariantId;
            $OrderProductVariant->Quantity = $Quantity;
            $OrderProductVariant->UnitPriceInclTax = $UnitPriceInclTax;
            $OrderProductVariant->UnitPriceExclTax = $UnitPriceExclTax;
            $OrderProductVariant->PriceInclTax = $PriceInclTax;
            $OrderProductVariant->PriceExclTax = $PriceExclTax;
            $OrderProductVariant->DiscountAmountInclTax = $DiscountAmountInclTax;
            $OrderProductVariant->DiscountAmountExclTax = $DiscountAmountExclTax;
            $OrderProductVariant->DownloadCount = $DownloadCount;
            $OrderProductVariant->IsDownloadActivated = $IsDownloadActivated;
            return $OrderProductVariant;
        }

       /**
        * Constructor for OrderProductVariant
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
            $this->_entityMap['Order'] = 'Order';
            $this->_entityMap['ProductVariant'] = 'ProductVariant';
            $this->Order = array();
            $this->ProductVariant = array();
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:ShoppingCartItem
    * @type:EntityType
    * @key:Id
    */
    class ShoppingCartItem extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ShoppingCartTypeId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $CustomerId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductVariantId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AttributesXml;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $CustomerEnteredPrice;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Quantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $UpdatedOnUtc;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:ShoppingCartItem_ProductVariant
        * @FromRole:ShoppingCartItem
        * @ToRole:ProductVariant
        */
        public $ProductVariant;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:ShoppingCartItem_Customer
        * @FromRole:ShoppingCartItem
        * @ToRole:Customer
        */
        public $Customer;
    

       /**
        * Function to create an instance of ShoppingCartItem
        * @param Edm.Int32 $Id
        * @param Edm.Int32 $ShoppingCartTypeId
        * @param Edm.Int32 $CustomerId
        * @param Edm.Int32 $ProductVariantId
        * @param Edm.Decimal $CustomerEnteredPrice
        * @param Edm.Int32 $Quantity
        * @param Edm.DateTime $CreatedOnUtc
        * @param Edm.DateTime $UpdatedOnUtc
        */
        public static function CreateShoppingCartItem(
            $Id, 
            $ShoppingCartTypeId, 
            $CustomerId, 
            $ProductVariantId, 
            $CustomerEnteredPrice, 
            $Quantity, 
            $CreatedOnUtc, 
            $UpdatedOnUtc)
        {   
            $ShoppingCartItem = new ShoppingCartItem();
            $ShoppingCartItem->Id = $Id;
            $ShoppingCartItem->ShoppingCartTypeId = $ShoppingCartTypeId;
            $ShoppingCartItem->CustomerId = $CustomerId;
            $ShoppingCartItem->ProductVariantId = $ProductVariantId;
            $ShoppingCartItem->CustomerEnteredPrice = $CustomerEnteredPrice;
            $ShoppingCartItem->Quantity = $Quantity;
            $ShoppingCartItem->CreatedOnUtc = $CreatedOnUtc;
            $ShoppingCartItem->UpdatedOnUtc = $UpdatedOnUtc;
            return $ShoppingCartItem;
        }

       /**
        * Constructor for ShoppingCartItem
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
            $this->_entityMap['ProductVariant'] = 'ProductVariant';
            $this->_entityMap['Customer'] = 'Customer';
            $this->ProductVariant = array();
            $this->Customer = array();
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:Customer
    * @type:EntityType
    * @key:Id
    */
    class Customer extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Guid
        */
        public $CustomerGuid;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1000
        * @FixedLength:false
        */
        public $Username;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:1000
        * @FixedLength:false
        */
        public $Email;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Password;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $PasswordFormatId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $PasswordSalt;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $AdminComment;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $LanguageId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $CurrencyId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $TaxDisplayTypeId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsTaxExempt;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $VatNumber;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $VatNumberStatusId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $SelectedPaymentMethodSystemName;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $CheckoutAttributes;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $DiscountCouponCode;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $GiftCardCouponCodes;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $UseRewardPointsDuringCheckout;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $TimeZoneId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $AffiliateId;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Active;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Deleted;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $IsSystemAccount;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $SystemName;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $LastIpAddress;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.DateTime
        */
        public $LastLoginDateUtc;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $LastActivityDateUtc;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $BillingAddress_Id;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.Int32
        */
        public $ShippingAddress_Id;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:Order_Customer
        * @FromRole:Customer
        * @ToRole:Order
        */
        public $Orders;
    
       /**
        * @Type:NavigationProperty
        * @Relationship:ShoppingCartItem_Customer
        * @FromRole:Customer
        * @ToRole:ShoppingCartItem
        */
        public $ShoppingCartItems;
    

       /**
        * Function to create an instance of Customer
        * @param Edm.Int32 $Id
        * @param Edm.Guid $CustomerGuid
        * @param Edm.Int32 $PasswordFormatId
        * @param Edm.Int32 $TaxDisplayTypeId
        * @param Edm.Boolean $IsTaxExempt
        * @param Edm.Int32 $VatNumberStatusId
        * @param Edm.Boolean $UseRewardPointsDuringCheckout
        * @param Edm.Boolean $Active
        * @param Edm.Boolean $Deleted
        * @param Edm.Boolean $IsSystemAccount
        * @param Edm.DateTime $CreatedOnUtc
        * @param Edm.DateTime $LastActivityDateUtc
        */
        public static function CreateCustomer(
            $Id, 
            $CustomerGuid, 
            $PasswordFormatId, 
            $TaxDisplayTypeId, 
            $IsTaxExempt, 
            $VatNumberStatusId, 
            $UseRewardPointsDuringCheckout, 
            $Active, 
            $Deleted, 
            $IsSystemAccount, 
            $CreatedOnUtc, 
            $LastActivityDateUtc)
        {   
            $Customer = new Customer();
            $Customer->Id = $Id;
            $Customer->CustomerGuid = $CustomerGuid;
            $Customer->PasswordFormatId = $PasswordFormatId;
            $Customer->TaxDisplayTypeId = $TaxDisplayTypeId;
            $Customer->IsTaxExempt = $IsTaxExempt;
            $Customer->VatNumberStatusId = $VatNumberStatusId;
            $Customer->UseRewardPointsDuringCheckout = $UseRewardPointsDuringCheckout;
            $Customer->Active = $Active;
            $Customer->Deleted = $Deleted;
            $Customer->IsSystemAccount = $IsSystemAccount;
            $Customer->CreatedOnUtc = $CreatedOnUtc;
            $Customer->LastActivityDateUtc = $LastActivityDateUtc;
            return $Customer;
        }

       /**
        * Constructor for Customer
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
            $this->_entityMap['Orders'] = 'Order';
            $this->_entityMap['ShoppingCartItems'] = 'ShoppingCartItem';
            $this->Orders = array();
            $this->ShoppingCartItems = array();
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:StockList
    * @type:EntityType
    * @key:Id
    * @key:Product
    * @key:Manufacturer
    * @key:StockQuantity
    * @key:Price
    * @key:Published
    * @key:CreatedOnUtc
    */
    class StockList extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $Id;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Name;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Product;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Description;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.String
        * @MaxLength:400
        * @FixedLength:false
        */
        public $Manufacturer;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Bezel;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Bracelet;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Dials;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $WatchMaterial;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $StockQuantity;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Decimal
        */
        public $Price;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Gender;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $HasPapers;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Certificated;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Boxed;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $YearOfManufacture;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Boolean
        */
        public $Published;
    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.DateTime
        */
        public $CreatedOnUtc;
    

       /**
        * Function to create an instance of StockList
        * @param Edm.Int32 $Id
        * @param Edm.String $Product
        * @param Edm.String $Manufacturer
        * @param Edm.Int32 $StockQuantity
        * @param Edm.Decimal $Price
        * @param Edm.Boolean $Published
        * @param Edm.DateTime $CreatedOnUtc
        */
        public static function CreateStockList(
            $Id, 
            $Product, 
            $Manufacturer, 
            $StockQuantity, 
            $Price, 
            $Published, 
            $CreatedOnUtc)
        {   
            $StockList = new StockList();
            $StockList->Id = $Id;
            $StockList->Product = $Product;
            $StockList->Manufacturer = $Manufacturer;
            $StockList->StockQuantity = $StockQuantity;
            $StockList->Price = $Price;
            $StockList->Published = $Published;
            $StockList->CreatedOnUtc = $CreatedOnUtc;
            return $StockList;
        }

       /**
        * Constructor for StockList
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:Bezel
    * @type:EntityType
    * @key:ProductAttributeId
    */
    class Bezel extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductAttributeId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Name;
    

       /**
        * Function to create an instance of Bezel
        * @param Edm.Int32 $ProductAttributeId
        */
        public static function CreateBezel(
            $ProductAttributeId)
        {   
            $Bezel = new Bezel();
            $Bezel->ProductAttributeId = $ProductAttributeId;
            return $Bezel;
        }

       /**
        * Constructor for Bezel
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:Bracelet
    * @type:EntityType
    * @key:ProductAttributeId
    */
    class Bracelet extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductAttributeId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Name;
    

       /**
        * Function to create an instance of Bracelet
        * @param Edm.Int32 $ProductAttributeId
        */
        public static function CreateBracelet(
            $ProductAttributeId)
        {   
            $Bracelet = new Bracelet();
            $Bracelet->ProductAttributeId = $ProductAttributeId;
            return $Bracelet;
        }

       /**
        * Constructor for Bracelet
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:Dial
    * @type:EntityType
    * @key:ProductAttributeId
    */
    class Dial extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductAttributeId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Name;
    

       /**
        * Function to create an instance of Dial
        * @param Edm.Int32 $ProductAttributeId
        */
        public static function CreateDial(
            $ProductAttributeId)
        {   
            $Dial = new Dial();
            $Dial->ProductAttributeId = $ProductAttributeId;
            return $Dial;
        }

       /**
        * Constructor for Dial
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * @class:WatchMaterial
    * @type:EntityType
    * @key:ProductAttributeId
    */
    class WatchMaterial extends Object
    {
        protected $_entityMap = array();
        protected $_entityKey = array();
        protected $_relLinks  = array();
        protected $_baseURI;

    
       /**
        * @Type:EntityProperty
        * NotNullable
        * @EdmType:Edm.Int32
        */
        public $ProductAttributeId;
    
       /**
        * @Type:EntityProperty
        * @EdmType:Edm.String
        * @MaxLength:Max
        * @FixedLength:false
        */
        public $Name;
    

       /**
        * Function to create an instance of WatchMaterial
        * @param Edm.Int32 $ProductAttributeId
        */
        public static function CreateWatchMaterial(
            $ProductAttributeId)
        {   
            $WatchMaterial = new WatchMaterial();
            $WatchMaterial->ProductAttributeId = $ProductAttributeId;
            return $WatchMaterial;
        }

       /**
        * Constructor for WatchMaterial
        */
        public function __construct($uri = "")
        {
            $this->_objectID = Guid::NewGuid();
            $this->_baseURI = $uri;
    
        }

       /**
        * overring getObjectID() functon of Object class
        */
        public function getObjectID()
        {
            return $this->_objectID;
        }

       /**
        * This function returns the entity keys of this entity.
        */
        public function getEntityKeys()
        {
            return $this->_entityKey;
        }

       /**
        * This function set the entity keys of this entity.
        */
        public function setEntityKeys($entityKey)
        {
            $this->_entityKey = $entityKey;
        }

       /**
        * This function returns the related links of this entity.
        */
        public function getRelatedLinks()
        {
            return $this->_relLinks;
        }

       /**
        * This function set the related links of this entity.
        */
        public function setRelatedLinks($relLinks)
        {
            $this->_relLinks = $relLinks;
        }

       /**
        * Function for getting Entity Type Name corrosponding to navigation Name
        */
        public function getActualEntityTypeName($key)
        {
            if (array_key_exists($key, $this->_entityMap))
            {
                return ($this->_entityMap[$key]);
            }
            return $key;
        }
    }
  
   /**
    * Container class BQWATCHESEntities, Namespace: BQWATCHESModel
    */
    class BQWATCHESEntities extends ObjectContext
    {
    
        protected $_Manufacturers;
        protected $_Products;
        protected $_ProductVariants;
        protected $_Orders;
        protected $_OrderProductVariants;
        protected $_ShoppingCartItems;
        protected $_Customers;
        protected $_StockLists;
        protected $_Bezels;
        protected $_Bracelets;
        protected $_Dials;
        protected $_WatchMaterials;
        
       /**
        * The constructor for BQWATCHESEntities accepting service URI
        */
        public function __construct($uri = "")
        {
            if(strlen($uri) == 0)
            {
                $uri = DEFAULT_ODATA_SERVICE_URL;
            }

            if (Utility::reverseFind($uri, '/') != strlen($uri) - 1)
            {
                $uri = $uri . '/';
            }

            $this->_baseURI = $uri;
            parent::__construct($this->_baseURI);
            $this->_entities = array(
                                "Manufacturers",
                                "Products",
                                "ProductVariants",
                                "Orders",
                                "OrderProductVariants",
                                "ShoppingCartItems",
                                "Customers",
                                "StockLists",
                                "Bezels",
                                "Bracelets",
                                "Dials",
                                "WatchMaterials");
            $this->_entitySet2Type = array(
                                            "manufacturers" => "Manufacturer", 
                                            "products" => "Product", 
                                            "productvariants" => "ProductVariant", 
                                            "orders" => "Order", 
                                            "orderproductvariants" => "OrderProductVariant", 
                                            "shoppingcartitems" => "ShoppingCartItem", 
                                            "customers" => "Customer", 
                                            "stocklists" => "StockList", 
                                            "bezels" => "Bezel", 
                                            "bracelets" => "Bracelet", 
                                            "dials" => "Dial", 
                                            "watchmaterials" => "WatchMaterial");
            $this->_entityType2Set = array(
                                            "manufacturer" => "Manufacturers", 
                                            "product" => "Products", 
                                            "productvariant" => "ProductVariants", 
                                            "order" => "Orders", 
                                            "orderproductvariant" => "OrderProductVariants", 
                                            "shoppingcartitem" => "ShoppingCartItems", 
                                            "customer" => "Customers", 
                                            "stocklist" => "StockLists", 
                                            "bezel" => "Bezels", 
                                            "bracelet" => "Bracelets", 
                                            "dial" => "Dials", 
                                            "watchmaterial" => "WatchMaterials");

            $this->_association = array();

    
            $this->_Manufacturers = new DataServiceQuery('/'.'Manufacturers', $this);
            $this->_Products = new DataServiceQuery('/'.'Products', $this);
            $this->_ProductVariants = new DataServiceQuery('/'.'ProductVariants', $this);
            $this->_Orders = new DataServiceQuery('/'.'Orders', $this);
            $this->_OrderProductVariants = new DataServiceQuery('/'.'OrderProductVariants', $this);
            $this->_ShoppingCartItems = new DataServiceQuery('/'.'ShoppingCartItems', $this);
            $this->_Customers = new DataServiceQuery('/'.'Customers', $this);
            $this->_StockLists = new DataServiceQuery('/'.'StockLists', $this);
            $this->_Bezels = new DataServiceQuery('/'.'Bezels', $this);
            $this->_Bracelets = new DataServiceQuery('/'.'Bracelets', $this);
            $this->_Dials = new DataServiceQuery('/'.'Dials', $this);
            $this->_WatchMaterials = new DataServiceQuery('/'.'WatchMaterials', $this);

        }

    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Manufacturers
         * @return DataServiceQuery
         */
        public function Manufacturers()
        {
            $this->_Manufacturers->ClearAllOptions();
            return $this->_Manufacturers;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Products
         * @return DataServiceQuery
         */
        public function Products()
        {
            $this->_Products->ClearAllOptions();
            return $this->_Products;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset ProductVariants
         * @return DataServiceQuery
         */
        public function ProductVariants()
        {
            $this->_ProductVariants->ClearAllOptions();
            return $this->_ProductVariants;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Orders
         * @return DataServiceQuery
         */
        public function Orders()
        {
            $this->_Orders->ClearAllOptions();
            return $this->_Orders;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset OrderProductVariants
         * @return DataServiceQuery
         */
        public function OrderProductVariants()
        {
            $this->_OrderProductVariants->ClearAllOptions();
            return $this->_OrderProductVariants;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset ShoppingCartItems
         * @return DataServiceQuery
         */
        public function ShoppingCartItems()
        {
            $this->_ShoppingCartItems->ClearAllOptions();
            return $this->_ShoppingCartItems;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Customers
         * @return DataServiceQuery
         */
        public function Customers()
        {
            $this->_Customers->ClearAllOptions();
            return $this->_Customers;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset StockLists
         * @return DataServiceQuery
         */
        public function StockLists()
        {
            $this->_StockLists->ClearAllOptions();
            return $this->_StockLists;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Bezels
         * @return DataServiceQuery
         */
        public function Bezels()
        {
            $this->_Bezels->ClearAllOptions();
            return $this->_Bezels;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Bracelets
         * @return DataServiceQuery
         */
        public function Bracelets()
        {
            $this->_Bracelets->ClearAllOptions();
            return $this->_Bracelets;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset Dials
         * @return DataServiceQuery
         */
        public function Dials()
        {
            $this->_Dials->ClearAllOptions();
            return $this->_Dials;
        }
    
        /**
         * Function returns DataServiceQuery reference for
         * the entityset WatchMaterials
         * @return DataServiceQuery
         */
        public function WatchMaterials()
        {
            $this->_WatchMaterials->ClearAllOptions();
            return $this->_WatchMaterials;
        }
    
       /**
        * Functions for adding object to the entityset/collection
        */
    
       /**
        * Add Manufacturers
        * @param Manufacturers $object
        */
      public function AddToManufacturers($object)
        {
            return parent::AddObject('Manufacturers', $object);
        }
    
       /**
        * Add Products
        * @param Products $object
        */
      public function AddToProducts($object)
        {
            return parent::AddObject('Products', $object);
        }
    
       /**
        * Add ProductVariants
        * @param ProductVariants $object
        */
      public function AddToProductVariants($object)
        {
            return parent::AddObject('ProductVariants', $object);
        }
    
       /**
        * Add Orders
        * @param Orders $object
        */
      public function AddToOrders($object)
        {
            return parent::AddObject('Orders', $object);
        }
    
       /**
        * Add OrderProductVariants
        * @param OrderProductVariants $object
        */
      public function AddToOrderProductVariants($object)
        {
            return parent::AddObject('OrderProductVariants', $object);
        }
    
       /**
        * Add ShoppingCartItems
        * @param ShoppingCartItems $object
        */
      public function AddToShoppingCartItems($object)
        {
            return parent::AddObject('ShoppingCartItems', $object);
        }
    
       /**
        * Add Customers
        * @param Customers $object
        */
      public function AddToCustomers($object)
        {
            return parent::AddObject('Customers', $object);
        }
    
       /**
        * Add StockLists
        * @param StockLists $object
        */
      public function AddToStockLists($object)
        {
            return parent::AddObject('StockLists', $object);
        }
    
       /**
        * Add Bezels
        * @param Bezels $object
        */
      public function AddToBezels($object)
        {
            return parent::AddObject('Bezels', $object);
        }
    
       /**
        * Add Bracelets
        * @param Bracelets $object
        */
      public function AddToBracelets($object)
        {
            return parent::AddObject('Bracelets', $object);
        }
    
       /**
        * Add Dials
        * @param Dials $object
        */
      public function AddToDials($object)
        {
            return parent::AddObject('Dials', $object);
        }
    
       /**
        * Add WatchMaterials
        * @param WatchMaterials $object
        */
      public function AddToWatchMaterials($object)
        {
            return parent::AddObject('WatchMaterials', $object);
        }
    

       /**
        * This function returns the entities.
        */
        public function getEntities()
        {
            return $this->_entities;
        }
    }
  
?>
  